### PR TITLE
Add login menu, main menu

### PR DESCRIPTION
**Pull request by TorbsT**
- Hopefully fix some naming and placement issues of some scripts
- Add a starting scene where the player "logs in". The username is not currently saved in any way
- Add the main menu. The main menu has two screens:
Lobby search: displays lobbies that can be joined by clicking. Can also create own lobby. The client will currently only check if there is a connection to the server, will not actually interact any further.
In lobby: displays players in that lobby. Currently displays a random amount of players. Can leave and go back to lobby search, or start the game.

### CODE REVIEW

**Review by Kem0sabe — COMMENTED** [review]
Ser bra ut. Er en UI bugg i create lobby der teksten med spiller, rolle og host overlapoper til tider.

Edit lol, feil merge request. men poenget står

Edit igjen: nei lol var rett

**Comment by TorbsT** [comment]
ah shiet, koss oppløsning bruke du?

**Comment by TorbsT** [comment]
Ska vær fiksa no!

**Review by Artewald — APPROVED** [review]

**Comment by Artewald** [comment]
Ser bra ut, men vi kommer nok til å måtte koordinere nærmere om RestAPIet når det nærmer seg 👍

**Pull request merged**
